mail.from=wissalkhalid503@gmail.com
mail.password=eqwahpwdaubxplds
mail.host=smtp.gmail.com
mail.port=587
```

Ajoute `mail.properties` dans `.gitignore` pour ne pas exposer ton mot de passe :
```
chrionline-server/src/main/resources/mail.properties